on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        python-ver: [3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          python -m pytest -v -s ./tests/
